source "https://rubygems.org"

gem 'googleauth', '~> 1.11'
gem 'google-cloud-storage', '~> 1.49'
gem 'google-cloud-secret_manager', '~> 1.4'
gem 'rest-client', '~> 2.1'
gem 'logger', '~> 1.6'
gem 'dotenv', '~> 3.1.0'
